//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoardApp.JobSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employer_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_apply_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_employment_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string job_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employer_name {
            get {
                return this.employer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.employer_nameField, value) != true)) {
                    this.employer_nameField = value;
                    this.RaisePropertyChanged("employer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_apply_link {
            get {
                return this.job_apply_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.job_apply_linkField, value) != true)) {
                    this.job_apply_linkField = value;
                    this.RaisePropertyChanged("job_apply_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_employment_type {
            get {
                return this.job_employment_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.job_employment_typeField, value) != true)) {
                    this.job_employment_typeField = value;
                    this.RaisePropertyChanged("job_employment_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_id {
            get {
                return this.job_idField;
            }
            set {
                if ((object.ReferenceEquals(this.job_idField, value) != true)) {
                    this.job_idField = value;
                    this.RaisePropertyChanged("job_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_location {
            get {
                return this.job_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.job_locationField, value) != true)) {
                    this.job_locationField = value;
                    this.RaisePropertyChanged("job_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_state {
            get {
                return this.job_stateField;
            }
            set {
                if ((object.ReferenceEquals(this.job_stateField, value) != true)) {
                    this.job_stateField = value;
                    this.RaisePropertyChanged("job_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string job_title {
            get {
                return this.job_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.job_titleField, value) != true)) {
                    this.job_titleField = value;
                    this.RaisePropertyChanged("job_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobSearch.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindJobs", ReplyAction="http://tempuri.org/IService/FindJobsResponse")]
        JobBoardApp.JobSearch.Job[] FindJobs(string jobTitle, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindJobs", ReplyAction="http://tempuri.org/IService/FindJobsResponse")]
        System.Threading.Tasks.Task<JobBoardApp.JobSearch.Job[]> FindJobsAsync(string jobTitle, string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : JobBoardApp.JobSearch.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<JobBoardApp.JobSearch.IService>, JobBoardApp.JobSearch.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JobBoardApp.JobSearch.Job[] FindJobs(string jobTitle, string location) {
            return base.Channel.FindJobs(jobTitle, location);
        }
        
        public System.Threading.Tasks.Task<JobBoardApp.JobSearch.Job[]> FindJobsAsync(string jobTitle, string location) {
            return base.Channel.FindJobsAsync(jobTitle, location);
        }
    }
}
