//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoard_Sonit.SalarySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalarySvc.ISalaryEstimator")]
    public interface ISalaryEstimator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryEstimator/EstimateSalary", ReplyAction="http://tempuri.org/ISalaryEstimator/EstimateSalaryResponse")]
        decimal EstimateSalary(string jobTitle, int yearsExperience);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryEstimator/EstimateSalary", ReplyAction="http://tempuri.org/ISalaryEstimator/EstimateSalaryResponse")]
        System.Threading.Tasks.Task<decimal> EstimateSalaryAsync(string jobTitle, int yearsExperience);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryEstimatorChannel : JobBoard_Sonit.SalarySvc.ISalaryEstimator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryEstimatorClient : System.ServiceModel.ClientBase<JobBoard_Sonit.SalarySvc.ISalaryEstimator>, JobBoard_Sonit.SalarySvc.ISalaryEstimator {
        
        public SalaryEstimatorClient() {
        }
        
        public SalaryEstimatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryEstimatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryEstimatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryEstimatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal EstimateSalary(string jobTitle, int yearsExperience) {
            return base.Channel.EstimateSalary(jobTitle, yearsExperience);
        }
        
        public System.Threading.Tasks.Task<decimal> EstimateSalaryAsync(string jobTitle, int yearsExperience) {
            return base.Channel.EstimateSalaryAsync(jobTitle, yearsExperience);
        }
    }
}
